package com.hypers.hm;

import android.animation.*;
import android.app.*;
import android.app.Activity;
import android.content.*;
import android.content.SharedPreferences;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.os.IBinder;
import android.os.RemoteException;
import android.os.Build;
import android.os.Parcel;
import android.os.ParcelFileDescriptor;
import android.os.Message;
import android.os.SystemClock;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.ArrayAdapter;
import android.widget.BaseAdapter;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import androidx.activity.EdgeToEdge;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import com.bumptech.glide.*;
import com.facebook.shimmer.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.*;
import org.json.*;
import org.lsposed.hiddenapibypass.library.*;
import rikka.shizuku.api.*;
import rikka.shizuku.provider.*;
import android.provider.Settings;
import android.Manifest;
import androidx.core.app.ActivityCompat;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.Environment;
import android.content.pm.ApplicationInfo;
import android.content.res.Configuration;



public class AddedActivity extends AppCompatActivity {
	
	private Timer _timer = new Timer();
	
	private String userId = "";
	private String appName = "";
	private String appPkg = "";
	private String pkgNew = "";
	private String id = "";
	private HashMap<String, Object> map = new HashMap<>();
	
	private ArrayList<String> list_app_name = new ArrayList<>();
	private ArrayList<String> list_app_package = new ArrayList<>();
	private ArrayList<HashMap<String, Object>> listmap = new ArrayList<>();
	
	private LinearLayout linear1;
	private LinearLayout linear2;
	private LinearLayout linear4;
	private LinearLayout linear10;
	private LinearLayout linear8;
	private EditText edittext1;
	private ProgressBar progressbar;
	private ListView listview1;
	
	private SharedPreferences user;
	private TimerTask t;
	private SharedPreferences totalApp;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		EdgeToEdge.enable(this);
		setContentView(R.layout.added);
		initialize(_savedInstanceState);
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		linear1 = findViewById(R.id.linear1);
		linear2 = findViewById(R.id.linear2);
		linear4 = findViewById(R.id.linear4);
		linear10 = findViewById(R.id.linear10);
		linear8 = findViewById(R.id.linear8);
		edittext1 = findViewById(R.id.edittext1);
		progressbar = findViewById(R.id.progressbar);
		listview1 = findViewById(R.id.listview1);
		user = getSharedPreferences("user", Activity.MODE_PRIVATE);
		totalApp = getSharedPreferences("totalApp", Activity.MODE_PRIVATE);
		
		linear1.setOnClickListener(_v -> finish());
	}
	
	private void initializeLogic() {
		if (getIntent().getBooleanExtra("dialogTheme",true)) {
			// To make the dialog corners round
			getWindow().getDecorView().setBackgroundResource(android.R.color.transparent);
			
			{
				android.graphics.drawable.GradientDrawable SketchUi = new android.graphics.drawable.GradientDrawable();
				int d = (int) getApplicationContext().getResources().getDisplayMetrics().density;
				SketchUi.setColor(Color.TRANSPARENT);SketchUi.setCornerRadius(d*20);
				
				((ViewGroup)getWindow().getDecorView()).getChildAt(0).setBackground(SketchUi);
			}
			
			// Codes Generated by SketchUi 
		}
		Window window = getWindow();
		
		if (android.os.Build.VERSION.SDK_INT >= 31) {
			
			
			window.setBackgroundBlurRadius(40);
			
			
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			
			android.view.WindowManager.LayoutParams p = window.getAttributes();
			p.dimAmount = 0.25f;
			window.setAttributes(p);
		}
		
		
		if (android.os.Build.VERSION.SDK_INT >= 35) {
			getWindow().setDecorFitsSystemWindows(false);
		}
		new LoadApplications().execute(new Void[0]);
		_pack();
		edittext1.addTextChangedListener(new TextWatcher() {
			@Override
			public void beforeTextChanged(CharSequence s, int start, int count, int after) {
				
			}
			
			@Override
			public void onTextChanged(CharSequence s, int start, int before, int count) {
				// Ini mirip onQueryTextChange
				filterApps(s.toString());
			}
			
			@Override
			public void afterTextChanged(Editable s) {
				// Tidak perlu pakai ini
			}
		});
		listview1.setScrollingCacheEnabled(false);
		listview1.setAnimationCacheEnabled(false);
		listview1.setHasTransientState(false);
		id = Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID);
		linear1.setBackgroundColor(0x700E0E0E);
		_sizetetap();
	}
	
	
	@Override
	public void onResume() {
		super.onResume();
		if (virtualConfig != null && virtualMetrics != null) {
			getResources().updateConfiguration(virtualConfig, virtualMetrics);
		}
	}
	public void _$SortListMap$(final ArrayList<HashMap<String, Object>> _listmap, final String _key, final boolean _isNumber, final boolean _ascending) {
		Collections.sort(_listmap, new Comparator<HashMap<String, Object>>() {
			public int compare(HashMap<String, Object> _compareMap1, HashMap<String, Object> _compareMap2) {
				if (_isNumber) {
					int _count1 = Integer.valueOf(_compareMap1.get(_key).toString());
					int _count2 = Integer.valueOf(_compareMap2.get(_key).toString());
					if (_ascending) {
						return _count1 < _count2 ? -1 : _count1 < _count2 ? 1 : 0;
					}
					else {
						return _count1 > _count2 ? -1 : _count1 > _count2 ? 1 : 0;
					}
				}
				else {
					if (_ascending) {
						return (_compareMap1.get(_key).toString()).compareTo(_compareMap2.get(_key).toString());
					}
					else {
						return (_compareMap2.get(_key).toString()).compareTo(_compareMap1.get(_key).toString());
					}
				}
			}
		});
	}
	
	
	public void _a() {
	}
	@Override
	public void setContentView(int layoutResID) {
		if (getIntent().getBooleanExtra("dialogTheme", true)) {
			supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
			setTheme(R.style.DialogTransparent);
			setFinishOnTouchOutside(true);
			
			try {
				java.lang.reflect.Method getActivityOptions = Activity.class.getDeclaredMethod("getActivityOptions");
				getActivityOptions.setAccessible(true);
				Object options = getActivityOptions.invoke(this);
				
				Class<?>[] classes = Activity.class.getDeclaredClasses();
				Class<?> translucentConversionListenerClazz = null;
				
				for (Class clazz : classes) {
					if (clazz.getSimpleName().contains("TranslucentConversionListener")) {
						translucentConversionListenerClazz = clazz;
						break;
					}
				}
				
				java.lang.reflect.Method convertToTranslucent = Activity.class.getDeclaredMethod(
				"convertToTranslucent",
				translucentConversionListenerClazz,
				ActivityOptions.class
				);
				convertToTranslucent.setAccessible(true);
				convertToTranslucent.invoke(this, null, options);
			} catch (Throwable t) {
				t.printStackTrace();
			}
		}
		
		super.setContentView(layoutResID);
		
		Window window = getWindow();
		
		if (window != null) {
			
			// bikin activity transparan
			window.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// posisi bottom seperti bottom sheet
			android.view.WindowManager.LayoutParams params = window.getAttributes();
			params.gravity = android.view.Gravity.BOTTOM;
			params.width = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.height = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.dimAmount = 0.4f;
			window.setAttributes(params);
			getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// hilangkan layar gelap
			window.setDimAmount(0.4f);
			
			// biar fullscreen tembus
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
		}
	}
	{
	}
	
	
	public void _$Load$() {
		list_app_name.clear();
		list_app_package.clear();
		listmap.clear();
		
		PackageManager pm = getApplicationContext().getPackageManager();
		
		for (android.content.pm.PackageInfo packageInfo : pm.getInstalledPackages(0)) {
			if ((packageInfo.applicationInfo.flags & android.content.pm.ApplicationInfo.FLAG_SYSTEM) == 0) {
				
				String pkgName = packageInfo.packageName;
				
				try {
					
					PackageInfo info = pm.getPackageInfo(pkgName, PackageManager.GET_ACTIVITIES);
					
					int category = packageInfo.applicationInfo.category;
					boolean isGame = (category == android.content.pm.ApplicationInfo.CATEGORY_GAME);
					
					if (!game || isGame) {
						String appName = packageInfo.applicationInfo.loadLabel(getPackageManager()).toString();
						
						list_app_name.add(appName);
						list_app_package.add(pkgName);
						
						map = new HashMap<>();
						map.put("app name", appName);
						map.put("package", pkgName);
						map.put("isGame", isGame);
						map.put("Game", isGame ? "Game" : "Other");
						listmap.add(map);
					}
					
				} catch (PackageManager.NameNotFoundException e) {
					
					File json = new File(Environment.getExternalStorageDirectory(), "ZYREX-TOOLS/data/Database/" + pkgName + ".json");
					
					if (json.exists()) {
						if (json.delete()) {
							
						} else {
							
						}
					} else {
						
					}
				}
			}
		}
		SharedPreferences.Editor editor = totalApp.edit();
		editor.putInt("App", listmap.size());
		editor.apply();
		jumlah = listmap.size();
		_$SortListMap$(listmap, "app name", false, true);
	}
	
	
	public void _pack() {
	}
	private class LoadApplications extends AsyncTask<Void, Integer, Void> {
		private int progressStatus = 0;
		
		@Override
		protected void onPreExecute() {
			super.onPreExecute();
			listview1.setVisibility(View.GONE);
			progressbar.setVisibility(View.VISIBLE);
			progressbar.setProgress(0); // mulai dari 0
		}
		
		@Override
		protected Void doInBackground(Void... voids) {
			for (int i = 0; i <= 100; i++) {
				try {
					Thread.sleep(20); // delay agar terlihat animasinya
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				publishProgress(i); // kirim nilai ke onProgressUpdate
			}
			
			_$Load$(); // fungsi loading utama kamu
			
			return null;
		}
		
		@Override
		protected void onProgressUpdate(Integer... values) {
			super.onProgressUpdate(values);
			progressbar.setProgress(values[0]);
		}
		
		@Override
		protected void onPostExecute(Void result) {
			super.onPostExecute(result);
			listview1.setAdapter(new Listview1Adapter(listmap));
			listview1.setVisibility(View.VISIBLE);
			progressbar.setVisibility(View.GONE);
		}
	}
	private ProgressDialog progress;
	{
	}
	
	
	public void _filtered() {
	}
	private void filterApps(String query) {
		String filter = query.trim().toLowerCase();
		ArrayList<HashMap<String, Object>> filteredList = new ArrayList<>();
		
		if (!filter.isEmpty()) {
			for (HashMap<String, Object> item : listmap) {
				String appName = item.get("app name").toString().toLowerCase();
				if (appName.contains(filter)) {
					filteredList.add(item);
				}
			}
		} else {
			filteredList.addAll(listmap);
		}
		
		listview1.setAdapter(new Listview1Adapter(filteredList));
		((BaseAdapter) listview1.getAdapter()).notifyDataSetChanged();
	}
	{
	}
	
	
	public void _variable() {
	}
	private int jumlah = 0;
	private int _position = 0;
	private Boolean game = false;
	{
	}
	
	
	public void _sizetetap() {
	}
	private static final int VIRTUAL_WIDTH = 625;
	private static final int VIRTUAL_HEIGHT = 1045;
	private Configuration virtualConfig;
	private DisplayMetrics virtualMetrics;
	
	@Override
	protected void attachBaseContext(Context newBase) {
		Context wrapped = wrapContext(newBase);
		virtualConfig = new Configuration(wrapped.getResources().getConfiguration());
		virtualMetrics = new DisplayMetrics();
		virtualMetrics.setTo(wrapped.getResources().getDisplayMetrics());
		super.attachBaseContext(wrapped);
	}
	
	private Context wrapContext(Context base) {
		DisplayMetrics dm = base.getResources().getDisplayMetrics();
		float scale = (float) dm.widthPixels / VIRTUAL_WIDTH;
		int targetDpi = (int) (scale * 240);
		
		Configuration config = new Configuration(base.getResources().getConfiguration());
		config.densityDpi = targetDpi;
		config.fontScale = 1.0f;
		config.screenWidthDp = VIRTUAL_WIDTH;
		config.screenHeightDp = VIRTUAL_HEIGHT;
		config.smallestScreenWidthDp = VIRTUAL_WIDTH;
		
		Context context = base.createConfigurationContext(config);
		
		DisplayMetrics metrics = context.getResources().getDisplayMetrics();
		metrics.density = targetDpi / 160f;
		metrics.densityDpi = targetDpi;
		metrics.scaledDensity = metrics.density;
		metrics.widthPixels = dm.widthPixels;
		metrics.heightPixels = dm.heightPixels;
		
		return context;
	}
	
	@Override
	public void applyOverrideConfiguration(Configuration overrideConfiguration) {
		if (overrideConfiguration != null && virtualConfig != null) {
			overrideConfiguration.setTo(virtualConfig);
		}
		super.applyOverrideConfiguration(overrideConfiguration);
	}
	
	@Override
	public Resources getResources() {
		Resources res = super.getResources();
		if (virtualConfig != null && virtualMetrics != null) {
			res.updateConfiguration(virtualConfig, virtualMetrics);
		}
		return res;
	}
	{
	}
	
	public class Listview1Adapter extends BaseAdapter {
		
		ArrayList<HashMap<String, Object>> _data;
		
		public Listview1Adapter(ArrayList<HashMap<String, Object>> _arr) {
			_data = _arr;
		}
		
		@Override
		public int getCount() {
			return _data.size();
		}
		
		@Override
		public HashMap<String, Object> getItem(int _index) {
			return _data.get(_index);
		}
		
		@Override
		public long getItemId(int _index) {
			return _index;
		}
		
		@Override
		public View getView(final int _position, View _v, ViewGroup _container) {
			LayoutInflater _inflater = getLayoutInflater();
			View _view = _v;
			if (_view == null) {
				_view = _inflater.inflate(R.layout.addlist, null);
			}
			
			final LinearLayout linear1 = _view.findViewById(R.id.linear1);
			final ImageView imageview1 = _view.findViewById(R.id.imageview1);
			final LinearLayout linear2 = _view.findViewById(R.id.linear2);
			final Switch switch1 = _view.findViewById(R.id.switch1);
			final TextView textview1 = _view.findViewById(R.id.textview1);
			
			try
			{
				Drawable app_icon = getPackageManager().getApplicationIcon(_data.get(_position).get("package").toString());
				
				imageview1.setImageDrawable(app_icon);
			}
			catch (android.content.pm.PackageManager.NameNotFoundException e) {
			}
			textview1.setText(_data.get((int) _position).get("app name").toString());
			userId = user.getString("KEY", "");
			appName = _data.get((int) _position).get("app name").toString();
			appPkg = _data.get((int) _position).get("package").toString();
			pkgNew = _data.get((int) _position).get("package").toString().replace(".", "_");
			try {
				String uri = _data.get((int)_position).get("package").toString();
				android.content.pm.PackageManager pm = getPackageManager();
				try {
					android.content.pm.PackageInfo pInfo = pm.getPackageInfo(uri, android.content.pm.PackageManager.GET_ACTIVITIES);
					String version = pInfo.versionName;
				}
				catch (android.content.pm.PackageManager.NameNotFoundException e) {
				}
			}
			catch (Exception e) {
			}
			user.edit().putString("us", _data.get((int) _position).get("app name").toString()).commit();
			user.edit().putString("pc", _data.get((int) _position).get("package").toString()).commit();
			switch1.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
				@Override
				public void onCheckedChanged(CompoundButton _param1, boolean _param2)  {
					final boolean _isChecked = _param2;
					if (_isChecked) {
						try {
							JSONObject json = new JSONObject();
							json.put("name", _data.get((int)_position).get("app name").toString());
							json.put("package", _data.get((int)_position).get("package").toString());
							json.put("game", _data.get((int)_position).get("Game").toString());
							json.put("Key", id);
							
							File tempJsonFile = new File(AddedActivity.this.getFilesDir(), _data.get((int)_position).get("package").toString() + ".json");
							FileOutputStream fos = new FileOutputStream(tempJsonFile);
							fos.write(json.toString(4).getBytes());
							fos.close();
							
							if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
								if (!Environment.isExternalStorageManager()) {
									Intent intent = new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION);
									startActivity(intent);
									return;
								}
							} else {
								
								ActivityCompat.requestPermissions(AddedActivity.this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
							}
							
							File targetDir = new File(Environment.getExternalStorageDirectory(), "ZYREX-TOOLS/data/Installed/");
							if (!targetDir.exists()) {
								targetDir.mkdirs();
							}
							
							File targetFile = new File(targetDir, _data.get((int)_position).get("package").toString() + ".json");
							
							FileInputStream in = new FileInputStream(tempJsonFile);
							OutputStream out = new FileOutputStream(targetFile);
							
							byte[] buffer = new byte[1024];
							int length;
							while ((length = in.read(buffer)) > 0) {
								out.write(buffer, 0, length);
							}
							
							in.close();
							out.close();
							
							Log.d("PluginJSON", "File copied to: " + targetFile.getAbsolutePath());
							
						} catch (Exception e) {
							Log.e("PluginJSON", "Error: " + e.getMessage());
						}
					}
					else {
						
						File json = new File(Environment.getExternalStorageDirectory(), "ZYREX-TOOLS/data/Installed/" + _data.get((int)_position).get("package").toString() + ".json");
						
						if (json.exists()) {
							if (json.delete()) {
								
							} else {
								
							}
						} else {
							
						}
					}
				}
			});
			textview1.setEllipsize(android.text.TextUtils.TruncateAt.MARQUEE);
			textview1.setMarqueeRepeatLimit(-1); 
			textview1.setSingleLine(true);
			textview1.setHorizontallyScrolling(true);
			textview1.setSelected(true);
			textview1.setHorizontalFadingEdgeEnabled(true);
			textview1.setFadingEdgeLength(50);
			try {
				
				File file = new File(Environment.getExternalStorageDirectory(), "ZYREX-TOOLS/data/Installed/" + _data.get((int)_position).get("package").toString() + ".json");
				
				FileInputStream fis = new FileInputStream(file);
				byte[] data = new byte[(int) file.length()];
				fis.read(data);
				fis.close();
				
				
				JSONObject obj = new JSONObject(new String(data));
				switch1.setChecked(true);
				
			} catch (Exception e) {
				switch1.setChecked(false);
			}
			
			
			return _view;
		}
	}
}
