package com.hypers.hm;
import com.hypers.hm.ExecEngine;

import android.animation.*;
import android.app.*;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.*;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.activity.EdgeToEdge;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import com.bumptech.glide.*;
import com.facebook.shimmer.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;
import org.lsposed.hiddenapibypass.library.*;
import rikka.shizuku.api.*;
import rikka.shizuku.provider.*;
import rikka.shizuku.Shizuku;
import android.content.pm.PackageManager;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.PackageManager.NameNotFoundException;
import android.content.ClipboardManager;
import android.content.ClipData;



public class EditActivity extends AppCompatActivity {
	
	private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER =
	new Shizuku.OnRequestPermissionResultListener() {
		@Override
		public void onRequestPermissionResult(int requestCode, int grantResult) {
			
			if (requestCode == 1000) {
				if (grantResult == PackageManager.PERMISSION_GRANTED) {
					
					android.widget.Toast.makeText(getApplicationContext(),
					"Shizuku Permission Granted", 0).show();
					
				} else {
					
					android.widget.Toast.makeText(getApplicationContext(),
					"Shizuku Permission Denied", 0).show();
					
				}
			}
			
		}
	};
	private String val = "";
	private String property = "";
	private String ceemde = "";
	private String delproperty = "";
	
	private LinearLayout linear9;
	private LinearLayout blinear1;
	private LinearLayout linear6;
	private LinearLayout blinear2;
	private LinearLayout blinear4;
	private LinearLayout blinear5;
	private LinearLayout linear8;
	private LinearLayout blinear7;
	private LinearLayout linear7;
	private ImageView imageview1;
	private TextView textview1;
	private TextView textview3;
	private TextView textview4;
	
	private SharedPreferences xmd;
	private AlertDialog.Builder d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		EdgeToEdge.enable(this);
		setContentView(R.layout.edit);
		initialize(_savedInstanceState);
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		linear9 = findViewById(R.id.linear9);
		blinear1 = findViewById(R.id.blinear1);
		linear6 = findViewById(R.id.linear6);
		blinear2 = findViewById(R.id.blinear2);
		blinear4 = findViewById(R.id.blinear4);
		blinear5 = findViewById(R.id.blinear5);
		linear8 = findViewById(R.id.linear8);
		blinear7 = findViewById(R.id.blinear7);
		linear7 = findViewById(R.id.linear7);
		imageview1 = findViewById(R.id.imageview1);
		textview1 = findViewById(R.id.textview1);
		textview3 = findViewById(R.id.textview3);
		textview4 = findViewById(R.id.textview4);
		xmd = getSharedPreferences("xmd", Activity.MODE_PRIVATE);
		d = new AlertDialog.Builder(this);
		
		imageview1.setOnClickListener(_v -> finish());
	}
	
	private void initializeLogic() {
		if (getIntent().getBooleanExtra("dialogTheme",true)) {
			// To make the dialog corners round
			getWindow().getDecorView().setBackgroundResource(android.R.color.transparent);
			
			{
				android.graphics.drawable.GradientDrawable SketchUi = new android.graphics.drawable.GradientDrawable();
				int d = (int) getApplicationContext().getResources().getDisplayMetrics().density;
				SketchUi.setColor(Color.TRANSPARENT);SketchUi.setCornerRadius(d*20);
				
				((ViewGroup)getWindow().getDecorView()).getChildAt(0).setBackground(SketchUi);
			}
			
			// Codes Generated by SketchUi 
		}
		Window window = getWindow();
		
		if (android.os.Build.VERSION.SDK_INT >= 31) {
			
			
			window.setBackgroundBlurRadius(40);
			
			
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			
			android.view.WindowManager.LayoutParams p = window.getAttributes();
			p.dimAmount = 0.15f;
			window.setAttributes(p);
		}
		linear9.setBackgroundColor(0x70212121);
		blinear1.setBackground(new GradientDrawable() { public GradientDrawable getIns(int a, int b, int c, int d) { this.setCornerRadius(a); this.setStroke(b, c); this.setColor(d); return this; } }.getIns((int)25, (int)0, 0x701976D2, 0xFF1A1A1A));
		blinear7.setBackground(new GradientDrawable() { public GradientDrawable getIns(int a, int b, int c, int d) { this.setCornerRadius(a); this.setStroke(b, c); this.setColor(d); return this; } }.getIns((int)50, (int)0, 0x701976D2, 0xFF00ACC1));
		ceemde = xmd.getString("cm-d", "");
		val = xmd.getString("values", "");
		property = xmd.getString("properties", "");
		delproperty = xmd.getString("delproperties", "");
		_sizetetap();
		blinear2.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View _view) {
				
				ClipboardManager clipboard = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
				String text = property + " " + ceemde + " " + val;
				clipboard.setPrimaryClip(ClipData.newPlainText("clipboard", text));
			}
		});
		blinear4.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View _view) {
				d.setTitle("change system command settings");
				d.setMessage(ceemde);
				final EditText 
				
				
				edittext
				
				
				= new EditText(
				
				
				EditActivity
				
				
				.this);
				LinearLayout.LayoutParams lpar = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);
				
				
				
				edittext.setLayoutParams(lpar);
				edittext.setText(val);
				
				
				d.setView(edittext);
				d.setPositiveButton("Set", new DialogInterface.OnClickListener() {
					@Override
					public void onClick(DialogInterface _dialog, int _which) {
						
						execSmart(property + " " + ceemde + " " +  edittext.getText().toString());
						SketchwareUtil.showMessage(getApplicationContext(), "Success Set " + ceemde);
						finish();
					}
				});
				d.setNegativeButton("cancel", new DialogInterface.OnClickListener() {
					@Override
					public void onClick(DialogInterface _dialog, int _which) {
						
					}
				});
				d.create().show();
			}
		});
		blinear5.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View _view) {
				execSmart(delproperty);
				SketchwareUtil.showMessage(getApplicationContext(), "Success Set " + ceemde);
				finish();
			}
		});
	}
	
	public void _AksesShizuku() {
		Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
		
		try {
			PackageManager packageManager = getPackageManager();
			PackageInfo packageInfo = packageManager.getPackageInfo("moe.shizuku.privileged.api", PackageManager.GET_ACTIVITIES);
			if (packageInfo != null) {
				
				if (Shizuku.pingBinder()) {
					if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
						
					} else {
						
					}
				}
			} else {
				
				
			}
		} catch (NameNotFoundException e) {
			
			
		}
	}
	
	
	public void _aksesPintarCmd() {
	}
	public boolean isRootAvailable() {
		try {
			process = Runtime.getRuntime().exec("su");
			DataOutputStream os = new DataOutputStream(process.getOutputStream());
			os.writeBytes("exit\n");
			os.flush();
			process.waitFor();
			return process.exitValue() == 0;
		} catch (Exception e) {
			return false;
		}
	}
	
	public boolean isShizukuAvailable() {
		try {
			return rikka.shizuku.Shizuku.pingBinder();
		} catch (Throwable e) {
			return false;
		}
	}
	
	public String execCommand(String cmd) {
		StringBuilder output = new StringBuilder();
		
		try {
			
			
			if (isRootAvailable()) {
				process = Runtime.getRuntime().exec(new String[]{"su", "-c", cmd});
			} else {
				// fallback ke shizuku (pastikan kamu sudah punya method shizukuExec)
				return shizukuExec(cmd);
			}
			
			BufferedReader reader = new BufferedReader(
			new InputStreamReader(process.getInputStream()));
			
			String line;
			while ((line = reader.readLine()) != null) {
				output.append(line).append("\n");
			}
			
			process.waitFor();
			
		} catch (Exception e) {
			return "Error: " + e.toString();
		}
		
		return output.toString();
	}
	
	public String execSmart(String cmd) {
		
		if (isRootAvailable()) {
			return execCommand(cmd);
		} else if (isShizukuAvailable()) {
			return shizukuExec(cmd);
		} else {
			return "No root / Shizuku not available";
		}
	}
	{
	}
	
	
	public void _var() {
	}
	private java.lang.Process process;
	{
	}
	
	
	public void _a() {
	}
	@Override
	public void setContentView(int layoutResID) {
		if (getIntent().getBooleanExtra("dialogTheme", true)) {
			supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
			setTheme(R.style.Theme_AppCompat_Light_Dialog);
			setFinishOnTouchOutside(true);
			
			try {
				java.lang.reflect.Method getActivityOptions = Activity.class.getDeclaredMethod("getActivityOptions");
				getActivityOptions.setAccessible(true);
				Object options = getActivityOptions.invoke(this);
				
				Class<?>[] classes = Activity.class.getDeclaredClasses();
				Class<?> translucentConversionListenerClazz = null;
				
				for (Class clazz : classes) {
					if (clazz.getSimpleName().contains("TranslucentConversionListener")) {
						translucentConversionListenerClazz = clazz;
						break;
					}
				}
				
				java.lang.reflect.Method convertToTranslucent = Activity.class.getDeclaredMethod(
				"convertToTranslucent",
				translucentConversionListenerClazz,
				ActivityOptions.class
				);
				convertToTranslucent.setAccessible(true);
				convertToTranslucent.invoke(this, null, options);
			} catch (Throwable t) {
				t.printStackTrace();
			}
		}
		
		super.setContentView(layoutResID);
		
		Window window = getWindow();
		
		if (window != null) {
			
			// bikin activity transparan
			window.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// posisi bottom seperti bottom sheet
			android.view.WindowManager.LayoutParams params = window.getAttributes();
			params.gravity = android.view.Gravity.BOTTOM;
			params.width = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.height = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.dimAmount = 0.4f;
			window.setAttributes(params);
			getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// hilangkan layar gelap
			window.setDimAmount(0.4f);
			
			// biar fullscreen tembus
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
		}
	}
	{
	}
	
	
	public void _shizukuexec() {
	}
	public boolean isShizukuReady() {
		
		if (!Shizuku.pingBinder()) return false;
		
		if (Shizuku.checkSelfPermission() != PackageManager.PERMISSION_GRANTED) {
			
			
			return false;
		}
		
		return true;
	}
	
	public String shizukuExec(String cmd) {
		
		try {
			
			process =
			ExecEngine.newProcess(new String[]{"sh","-c",cmd});
			
			InputStream in = process.getInputStream();
			
			byte[] buffer = new byte[1024];
			int len;
			StringBuilder out = new StringBuilder();
			
			while ((len = in.read(buffer)) > 0) {
				out.append(new String(buffer, 0, len));
			}
			
			process.waitFor();
			process.destroy();
			
			return out.toString();
			
		} catch (Exception e) {
			return "";
		}
	}
	{
	}
	
	
	public void _sizetetap() {
	}
	private static final int VIRTUAL_WIDTH = 625;
	private static final int VIRTUAL_HEIGHT = 1045;
	private Configuration virtualConfig;
	private DisplayMetrics virtualMetrics;
	
	@Override
	protected void attachBaseContext(Context newBase) {
		Context wrapped = wrapContext(newBase);
		virtualConfig = new Configuration(wrapped.getResources().getConfiguration());
		virtualMetrics = new DisplayMetrics();
		virtualMetrics.setTo(wrapped.getResources().getDisplayMetrics());
		super.attachBaseContext(wrapped);
	}
	
	private Context wrapContext(Context base) {
		DisplayMetrics dm = base.getResources().getDisplayMetrics();
		float scale = (float) dm.widthPixels / VIRTUAL_WIDTH;
		int targetDpi = (int) (scale * 180);
		
		Configuration config = new Configuration(base.getResources().getConfiguration());
		config.densityDpi = targetDpi;
		config.fontScale = 1.0f;
		config.screenWidthDp = VIRTUAL_WIDTH;
		config.screenHeightDp = VIRTUAL_HEIGHT;
		config.smallestScreenWidthDp = VIRTUAL_WIDTH;
		
		Context context = base.createConfigurationContext(config);
		
		DisplayMetrics metrics = context.getResources().getDisplayMetrics();
		metrics.density = targetDpi / 160f;
		metrics.densityDpi = targetDpi;
		metrics.scaledDensity = metrics.density;
		metrics.widthPixels = dm.widthPixels;
		metrics.heightPixels = dm.heightPixels;
		
		return context;
	}
	
	@Override
	public void applyOverrideConfiguration(Configuration overrideConfiguration) {
		if (overrideConfiguration != null && virtualConfig != null) {
			overrideConfiguration.setTo(virtualConfig);
		}
		super.applyOverrideConfiguration(overrideConfiguration);
	}
	
	@Override
	public Resources getResources() {
		Resources res = super.getResources();
		if (virtualConfig != null && virtualMetrics != null) {
			res.updateConfiguration(virtualConfig, virtualMetrics);
		}
		return res;
	}
	{
	}
	
}
