package com.hypers.hm;
import com.hypers.hm.ExecEngine;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.os.IBinder;
import android.os.RemoteException;
import android.os.Build;
import android.os.Parcel;
import android.os.ParcelFileDescriptor;
import android.os.Message;
import android.os.SystemClock;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.ArrayAdapter;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import com.bumptech.glide.*;
import com.facebook.shimmer.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;
import org.lsposed.hiddenapibypass.library.*;
import rikka.shizuku.api.*;
import rikka.shizuku.provider.*;
import rikka.shizuku.Shizuku;
import android.content.pm.PackageManager;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.PackageManager.NameNotFoundException;

import java.lang.Process;

import android.provider.Settings;
import android.Manifest;
import androidx.core.app.ActivityCompat;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.Environment;
import android.content.pm.ApplicationInfo;
import android.content.res.Configuration;



public class TaskActivity extends AppCompatActivity {
	
	private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER =
	new Shizuku.OnRequestPermissionResultListener() {
		@Override
		public void onRequestPermissionResult(int requestCode, int grantResult) {
			
			if (requestCode == 1000) {
				if (grantResult == PackageManager.PERMISSION_GRANTED) {
					
					android.widget.Toast.makeText(getApplicationContext(),
					"Shizuku Permission Granted", 0).show();
					
				} else {
					
					android.widget.Toast.makeText(getApplicationContext(),
					"Shizuku Permission Denied", 0).show();
					
				}
			}
			
		}
	};
	
	private LinearLayout linear1;
	private LinearLayout linear2;
	private LinearLayout linear3;
	private LinearLayout linear4;
	private LinearLayout linear5;
	private ImageView imageview1;
	private TextView textview1;
	private TextView textview2;
	private ListView listview1;
	private ProgressBar progressbar;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.task);
		initialize(_savedInstanceState);
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		linear1 = findViewById(R.id.linear1);
		linear2 = findViewById(R.id.linear2);
		linear3 = findViewById(R.id.linear3);
		linear4 = findViewById(R.id.linear4);
		linear5 = findViewById(R.id.linear5);
		imageview1 = findViewById(R.id.imageview1);
		textview1 = findViewById(R.id.textview1);
		textview2 = findViewById(R.id.textview2);
		listview1 = findViewById(R.id.listview1);
		progressbar = findViewById(R.id.progressbar);
		
		linear1.setOnClickListener(_v -> finish());
	}
	
	private void initializeLogic() {
		if (getIntent().getBooleanExtra("dialogTheme",true)) {
			// To make the dialog corners round
			getWindow().getDecorView().setBackgroundResource(android.R.color.transparent);
			
			{
				android.graphics.drawable.GradientDrawable SketchUi = new android.graphics.drawable.GradientDrawable();
				int d = (int) getApplicationContext().getResources().getDisplayMetrics().density;
				SketchUi.setColor(Color.TRANSPARENT);SketchUi.setCornerRadius(d*20);
				
				((ViewGroup)getWindow().getDecorView()).getChildAt(0).setBackground(SketchUi);
			}
			
			// Codes Generated by SketchUi 
		}
		Window window = getWindow();
		
		if (android.os.Build.VERSION.SDK_INT >= 31) {
			
			
			window.setBackgroundBlurRadius(40);
			
			
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			
			android.view.WindowManager.LayoutParams p = window.getAttributes();
			p.dimAmount = 0.25f;
			window.setAttributes(p);
		}
		
		if (android.os.Build.VERSION.SDK_INT >= 35) {
			getWindow().setDecorFitsSystemWindows(false);
		}
		linear2.setBackground(new android.graphics.drawable.GradientDrawable(
		android.graphics.drawable.GradientDrawable.Orientation.TOP_BOTTOM,
		new int[]{0x701A1A1A, 0x700E0E0E}
		) {{
				setCornerRadius(28);
			}});
		listview1.setDivider(null);
		listview1.setFastScrollEnabled(true);
		listview1.setVerticalScrollBarEnabled(false);
		new LoadApplications().execute(new Void[0]);
		isLoaded = false;
		loadActiveTasks();
		if (Shizuku.pingBinder()) {
			
			if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
				isLoaded = false;
				loadActiveTasks();
			} else {
				Shizuku.requestPermission(0);
			}
			
		}
		linear1.setBackgroundColor(0x700E0E0E);
	}
	
	
	@Override
	public void onDestroy() {
		super.onDestroy();
		handler.removeCallbacksAndMessages(null);
	}
	public void _task() {
	}
	private ArrayList<HashMap<String, Object>> listmap = new ArrayList<>();
	private HashMap<String, Drawable> iconCache = new HashMap<>();
	private HashMap<String, String> nameCache = new HashMap<>();
	private boolean isLoaded = false;
	
	
	public void loadActiveTasks() {
		if (isLoaded) return;
		
		new Thread(() -> {
			ArrayList<HashMap<String, Object>> tempList = new ArrayList<>();
			try {
				Process ps = ExecEngine.newProcess(new String[]{"sh", "-c", "ps -A -o PID,USER,%CPU,RSS,NAME | grep u0_a"});
				BufferedReader reader = new BufferedReader(new InputStreamReader(ps.getInputStream()));
				String line;
				while ((line = reader.readLine()) != null) {
					line = line.trim();
					String[] p = line.split("\\s+");
					if (p.length < 5) continue;
					
					String pid = p[0];
					String cpu = p[2];
					String ram = p[3];
					String pkg = cleanPackage(p[p.length - 1]);
					
					if (!pkg.isEmpty() && pkg.contains(".") && isUserApp(pkg)) {
						HashMap<String, Object> map = new HashMap<>();
						
						if (!nameCache.containsKey(pkg)) {
							nameCache.put(pkg, getAppName(pkg));
							iconCache.put(pkg, getAppIcon(pkg));
						}
						
						map.put("pid", pid);
						map.put("pkg", pkg);
						map.put("name", nameCache.get(pkg));
						map.put("cpu", cpu);
						map.put("ram", formatRam(ram));
						map.put("icon_drawable", iconCache.get(pkg)); 
						
						tempList.add(map);
					}
				}
				ps.waitFor();
				isLoaded = true;
			} catch (Exception e) {
				e.printStackTrace();
			}
			
			runOnUiThread(() -> {
				listmap.clear();
				listmap.addAll(tempList);
				if (listview1.getAdapter() == null) {
					listview1.setAdapter(new Listview1Adapter(listmap));
				} else {
					((BaseAdapter)listview1.getAdapter()).notifyDataSetChanged();
				}
			});
		}).start();
	}
	
	
	
	public String formatRam(String rss) {
		try {
			long kb = Long.parseLong(rss.replaceAll("[^0-9]", ""));
			return (kb / 1024) + " MB";
		} catch (Exception e) {
			return "0 MB";
		}
	}
	
	public void killProcess(String pid, String pkg) {
		new Thread(() -> {
			try {
				
				
				ExecEngine.newProcess(new String[]{"sh", "-c", "kill -9 " + pid});
				
				
				ExecEngine.newProcess(new String[]{"sh", "-c", "am force-stop " + pkg});
				
			} catch (Exception e) {
				e.printStackTrace();
			}
		}).start();
	}
	
	public String getAppName(String pkg) {
		try {
			PackageManager pm = getPackageManager();
			ApplicationInfo ai = pm.getApplicationInfo(pkg, 0);
			return pm.getApplicationLabel(ai).toString();
		} catch (Exception e) {
			return pkg;
		}
	}
	
	public String cleanPackage(String name) {
		try {
			
			if (name.contains(":")) {
				name = name.split(":")[0];
			}
			
			// ambil hanya string package valid
			if (!name.matches(".*\\..*")) return "";
			
			return name.trim();
			
		} catch (Exception e) {
			return "";
		}
	}
	
	public Drawable getAppIcon(String pkg) {
		if (iconCache.containsKey(pkg)) return iconCache.get(pkg); // Ambil dari cache
		try {
			Drawable icon = getPackageManager().getApplicationIcon(pkg);
			iconCache.put(pkg, icon); // Simpan ke cache
			return icon;
		} catch (Exception e) {
			return getResources().getDrawable(R.drawable.hypers);
		}
	}
	
	public boolean isUserApp(String pkg) {
		try {
			ApplicationInfo ai = getPackageManager().getApplicationInfo(pkg, 0);
			return (ai.flags & ApplicationInfo.FLAG_SYSTEM) == 0
			|| (ai.flags & ApplicationInfo.FLAG_UPDATED_SYSTEM_APP) != 0;
		} catch (Exception e) {
			return false;
		}
	}
	private Handler handler = new Handler();
	
	public void startAutoRefresh() {
		handler.postDelayed(new Runnable() {
			@Override
			public void run() {
				
				handler.postDelayed(this, 2500);
			}
		}, 2500);
	}
	{
	}
	
	
	public void _AksesShizuku() {
		Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
		
		try {
			PackageManager packageManager = getPackageManager();
			PackageInfo packageInfo = packageManager.getPackageInfo("moe.shizuku.privileged.api", PackageManager.GET_ACTIVITIES);
			if (packageInfo != null) {
				
				if (Shizuku.pingBinder()) {
					if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
						
					} else {
						
					}
				}
			} else {
				
				
			}
		} catch (NameNotFoundException e) {
			
			
		}
	}
	
	
	public void _aksesPintarCmd() {
	}
	private java.lang.Process process;
	
	public boolean isRootAvailable() {
		try {
			process = Runtime.getRuntime().exec("su");
			DataOutputStream os = new DataOutputStream(process.getOutputStream());
			os.writeBytes("exit\n");
			os.flush();
			process.waitFor();
			return process.exitValue() == 0;
		} catch (Exception e) {
			return false;
		}
	}
	
	public boolean isShizukuAvailable() {
		try {
			return rikka.shizuku.Shizuku.pingBinder();
		} catch (Throwable e) {
			return false;
		}
	}
	
	public String execCommand(String cmd) {
		StringBuilder output = new StringBuilder();
		
		try {
			
			
			if (isRootAvailable()) {
				process = Runtime.getRuntime().exec(new String[]{"su", "-c", cmd});
			} else {
				// fallback ke shizuku (pastikan kamu sudah punya method shizukuExec)
				return shizukuExec(cmd);
			}
			
			BufferedReader reader = new BufferedReader(
			new InputStreamReader(process.getInputStream()));
			
			String line;
			while ((line = reader.readLine()) != null) {
				output.append(line).append("\n");
			}
			
			process.waitFor();
			
		} catch (Exception e) {
			return "Error: " + e.toString();
		}
		
		return output.toString();
	}
	
	private String shizukuExec(String cmd) {
		try {
			Process process = ExecEngine.newProcess(new String[]{"sh", "-c", cmd});
			
			BufferedReader reader = new BufferedReader(
			new InputStreamReader(process.getInputStream())
			);
			
			StringBuilder out = new StringBuilder();
			String line;
			
			while ((line = reader.readLine()) != null) {
				out.append(line).append("\n");
			}
			
			return out.toString();
			
		} catch (Exception e) {
			return e.toString();
		}
	}
	
	public String execSmart(String cmd) {
		if (isRootAvailable()) {
			return execCommand(cmd);
		} 
		
		com.hypers.hm.debug.ADB adb = com.hypers.hm.debug.ADB.getInstance(this);
		if (adb.started.getValue() != null && adb.started.getValue()) {
			try {
				adb.sendToShellProcess(cmd);
				return "Executed via ADB"; 
			} catch (Exception e) {
			}
		}
		
		// 3. Cek Shizuku (Fallback Terakhir)
		if (isShizukuAvailable()) {
			return shizukuExec(cmd);
		} 
		
		// 4. Jika semua gagal
		return "Error: No Root, ADB, or Shizuku available";
	}
	
	{
	}
	
	
	public void _a() {
	}
	@Override
	public void setContentView(int layoutResID) {
		if (getIntent().getBooleanExtra("dialogTheme", true)) {
			supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
			setTheme(R.style.DialogTransparent);
			setFinishOnTouchOutside(true);
			
			try {
				java.lang.reflect.Method getActivityOptions = Activity.class.getDeclaredMethod("getActivityOptions");
				getActivityOptions.setAccessible(true);
				Object options = getActivityOptions.invoke(this);
				
				Class<?>[] classes = Activity.class.getDeclaredClasses();
				Class<?> translucentConversionListenerClazz = null;
				
				for (Class clazz : classes) {
					if (clazz.getSimpleName().contains("TranslucentConversionListener")) {
						translucentConversionListenerClazz = clazz;
						break;
					}
				}
				
				java.lang.reflect.Method convertToTranslucent = Activity.class.getDeclaredMethod(
				"convertToTranslucent",
				translucentConversionListenerClazz,
				ActivityOptions.class
				);
				convertToTranslucent.setAccessible(true);
				convertToTranslucent.invoke(this, null, options);
			} catch (Throwable t) {
				t.printStackTrace();
			}
		}
		
		super.setContentView(layoutResID);
		
		Window window = getWindow();
		
		if (window != null) {
			
			// bikin activity transparan
			window.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// posisi bottom seperti bottom sheet
			android.view.WindowManager.LayoutParams params = window.getAttributes();
			params.gravity = android.view.Gravity.BOTTOM;
			params.width = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.height = android.view.WindowManager.LayoutParams.MATCH_PARENT;
			params.dimAmount = 0.4f;
			window.setAttributes(params);
			getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);
			// hilangkan layar gelap
			window.setDimAmount(0.4f);
			
			// biar fullscreen tembus
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
			window.addFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
		}
	}
	{
	}
	
	
	public void _click(final View _view) {
		RippleDrawable ripple = new RippleDrawable(
		ColorStateList.valueOf(Color.parseColor("#33FFFFFF")),
		_view.getBackground(),
		null
		);
		
		_view.setBackground(ripple);
		_view.setClickable(true);
		_view.setFocusable(true);
	}
	
	
	public void _taskLoad() {
	}
	private class LoadApplications extends AsyncTask<Void, Integer, Void> {
		private int progressStatus = 0;
		
		@Override
		protected void onPreExecute() {
			super.onPreExecute();
			listview1.setVisibility(View.GONE);
			progressbar.setVisibility(View.VISIBLE);
			progressbar.setProgress(0); // mulai dari 0
		}
		
		@Override
		protected Void doInBackground(Void... voids) {
			for (int i = 0; i <= 100; i++) {
				try {
					Thread.sleep(20); // delay agar terlihat animasinya
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				publishProgress(i); // kirim nilai ke onProgressUpdate
			}
			
			isLoaded = false;
			loadActiveTasks();
			
			return null;
		}
		
		@Override
		protected void onProgressUpdate(Integer... values) {
			super.onProgressUpdate(values);
			progressbar.setProgress(values[0]);
		}
		
		@Override
		protected void onPostExecute(Void result) {
			super.onPostExecute(result);
			
			listview1.setVisibility(View.VISIBLE);
			progressbar.setVisibility(View.GONE);
		}
	}
	private ProgressDialog progress;
	{
	}
	
	public class Listview1Adapter extends BaseAdapter {
		
		ArrayList<HashMap<String, Object>> _data;
		
		public Listview1Adapter(ArrayList<HashMap<String, Object>> _arr) {
			_data = _arr;
		}
		
		@Override
		public int getCount() {
			return _data.size();
		}
		
		@Override
		public HashMap<String, Object> getItem(int _index) {
			return _data.get(_index);
		}
		
		@Override
		public long getItemId(int _index) {
			return _index;
		}
		
		@Override
		public View getView(final int _position, View _v, ViewGroup _container) {
			LayoutInflater _inflater = getLayoutInflater();
			View _view = _v;
			if (_view == null) {
				_view = _inflater.inflate(R.layout.taskpid, null);
			}
			
			final LinearLayout linear1 = _view.findViewById(R.id.linear1);
			final LinearLayout linear2 = _view.findViewById(R.id.linear2);
			final ImageView imageview1 = _view.findViewById(R.id.imageview1);
			final LinearLayout linear3 = _view.findViewById(R.id.linear3);
			final LinearLayout linear8 = _view.findViewById(R.id.linear8);
			final LinearLayout linear5 = _view.findViewById(R.id.linear5);
			final TextView textview1 = _view.findViewById(R.id.textview1);
			final TextView textview2 = _view.findViewById(R.id.textview2);
			final TextView textview3 = _view.findViewById(R.id.textview3);
			final TextView textview4 = _view.findViewById(R.id.textview4);
			final LinearLayout linear9 = _view.findViewById(R.id.linear9);
			final TextView textview5 = _view.findViewById(R.id.textview5);
			
			linear9.setBackground(new GradientDrawable() { public GradientDrawable getIns(int a, int b, int c, int d) { this.setCornerRadius(a); this.setStroke(b, c); this.setColor(d); return this; } }.getIns((int)28, (int)1, 0xFF00ACC1, 0x5000ACC1));
			textview1.setText(_data.get((int) _position).get("name").toString());
			textview2.setText(_data.get((int) _position).get("pkg").toString());
			textview3.setText("CPU " + _data.get((int) _position).get("cpu").toString() + "%");
			textview4.setText("RAM " + _data.get((int) _position).get("ram").toString());
			
			
			try
			{
				Drawable app_icon = getPackageManager().getApplicationIcon(_data.get(_position).get("pkg").toString());
				
				imageview1.setImageDrawable(app_icon);
			}
			catch (android.content.pm.PackageManager.NameNotFoundException e) {
			}
			textview1.setEllipsize(TextUtils.TruncateAt.MARQUEE);
			textview1.setMarqueeRepeatLimit(-1);
			textview1.setSingleLine(true);
			textview1.setHorizontallyScrolling(true);
			textview1.setSelected(true);
			
			textview1.setHorizontalFadingEdgeEnabled(true);
			textview1.setFadingEdgeLength(50);
			
			textview2.setEllipsize(TextUtils.TruncateAt.MARQUEE);
			textview2.setMarqueeRepeatLimit(-1);
			textview2.setSingleLine(true);
			textview2.setHorizontallyScrolling(true);
			textview2.setSelected(true);
			
			textview2.setHorizontalFadingEdgeEnabled(true);
			textview2.setFadingEdgeLength(50);
			linear9.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View _view) {
					_click(linear9);
					String pid = _data.get((int) _position).get("pid").toString();
					String pkg = _data.get((int) _position).get("pkg").toString();
					
					killProcess(pid, pkg);
					
					Toast.makeText(getApplicationContext(),
					"Killed task : " + pkg,
					Toast.LENGTH_SHORT).show();
					
					isLoaded = false;
					loadActiveTasks();
				}
			});
			
			return _view;
		}
	}
}
